---
title: "Keywords for Elon Musk"
author: "Louie Chen"
date: "November 14, 2018"
output: html_document
runtime: shiny
---

##研究動機與目的
目前已經知道許多媒體在報導政治人物或政治事件時會透過自己主觀的想法將報導內容偏向自己支持的一方，但是在比較沒有政治色彩的其他人物報導上會不會有這種現象呢? Tesla CEO: Elon Musk是一個企業人士中較為一體兩面的人，優點缺點鮮明，因此想要捧他或想要黑他都很可以發揮，因此我挑選這個人作為研究題材。希望透過這個人看看每個媒體的報導的著重點是否受其立場影響。
```{r}
library(shiny)

#Set Language as traditional Chinese
Sys.setlocale(category = "LC_ALL", locale = "cht")

# Define UI for application that draws a histogram
ui <- fluidPage( 
  
  tabsetPanel(
    tabPanel("Common Keywords from Different Media",

      # Application title
      #titlePanel("Old Faithful Geyser Data"),
  
      # Sidebar with a slider input for number of bins 
      sidebarLayout(
        sidebarPanel(
          radioButtons("Media", "Choose Media:",
                       choices = list("Techorange" = "Techorange.csv", "BBC Chinese" = "BBC_Chinese.csv",
                                      "Epochtimes" = "Epochtimes.csv", "Inside" = "Inside.csv"),selected = "Techorange.csv"),
          sliderInput("no.keyword.BBC.in",
                      "Number of Keywords:",
                      min = 1,
                      max = 50,
                      value = 25)
        ),
    
        # Show a plot of the generated distribution
        mainPanel(
          plotOutput("keyword.BBC.out")
        )
      )
    ),
    tabPanel("Overall Keywords", 
 
      sidebarLayout(
       sidebarPanel(
         sliderInput("over.in",
                     "Number of Keywords:",
                     min = 1,
                     max = 50,
                     value = 25)
         ),
               
         # Show a plot of the generated distribution
         mainPanel(
           plotOutput("over.out")
         )
      )
    ),
    tabPanel("Classification of Keywords", 
    
      sidebarLayout(
        sidebarPanel(
          radioButtons("class.in", "Choose Cluster:",
                       choices = list("1" = 1, "2"= 2,
                                      "3" = 3, "4" = 4, "All" = "All"),selected = "All")
        ),
               
        # Show a plot of the generated distribution
        mainPanel(
          fluidRow(
            #img(src = "2.jpg", height = 400, width = 600),
            column(3, imageOutput("img.out"))
          ),
          fluidRow(
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            br(),
            h3("Example Words in Cluster:"),
            column(3, tableOutput("class.out"))
          )
        )
      )         
    ),
    tabPanel("Prediction of Article Source", 
             
             sidebarLayout(
               sidebarPanel(
                 textInput("artic.in", h3("Article about Elon Musk:"), 
                           value = "Paste text...")
               ),
               
               # Show a plot of the generated distribution
               mainPanel(
                 br(),
                 h3("Cut words:"),
                 textOutput("artic.txt.out"),
                 br(),
                 br(),
                 br(),
                 h3("Possible Cluster of Keywords:"),
                 tableOutput("artic.out"),
                 h3("Prediction Matrix:"),
                 imageOutput("img.pred.out")
               )
             )
    )
  )
)

server <- function(input, output) {
  
  output$keyword.BBC.out <- renderPlot({
    
    dat <- read.csv(input$Media) 
    freq_table <- dat[1:input$no.keyword.BBC.in, 2:3]
    
    #Draw Plot
    library(ggplot2)
    freq_table$Var1 <- factor(freq_table$Var1, levels = freq_table$Var1)
    ggplot(data = freq_table, aes(x = Var1, y = Freq)) +
      geom_bar(stat="identity", width = 0.5, fill = "blue") + 
      labs(title="KeyWords Ranking for Elon Musk", 
           subtitle="Sorted Bar Chart") + 
      theme(axis.text.x = element_text(angle=65, vjust=0.6))
    
  })
  
  output$over.out <- renderPlot({
    
    dat <- read.csv("./Overall_freq.csv")
    freq_table <- dat[1:input$over.in, 2:3]
    
    #Draw Plot
    library(ggplot2)
    freq_table$Var1 <- factor(freq_table$Var1, levels = freq_table$Var1)
    ggplot(data = freq_table, aes(x = Var1, y = Freq)) +
      geom_bar(stat="identity", width = 0.5, fill = "blue") + 
      labs(title="Overall Keywords Ranking for Elon Musk", 
           subtitle="Sorted Bar Chart") + 
      theme(axis.text.x = element_text(angle=65, vjust=0.6))
  })
  
  output$img.out <- renderImage({
    # When input$class.in is 1, filename is ./www/1.jpg
    filename <- normalizePath(file.path('./www', paste(input$class.in, '.jpg', sep='')))
    
    # Return a list containing the filename
    list(src = filename)
  }, deleteFile = FALSE)
  
  output$class.out <- renderTable({
    dat <- read.csv("./cluster_data.csv")
    #file.exists("cluster_data.csv")
    
    #dat[1:3,1:2]
    n = 0
    
    if(input$class.in == "All"){
      dat[1:30, 1]
    }else if(input$class.in == 1){
      dat[1:30, 4]
    }else if(input$class.in == 2){
      dat[1:30, 7]
    }else if(input$class.in == 3){
      dat[1:30, 10]
    }else if(input$class.in == 4){
      dat[1:30, 13]
    }
  })
  
  output$artic.txt.out <- renderText({
    library(jiebaR)
    mixseg = worker()
    seg <- mixseg[input$artic.in]
    
    #去掉只包含一個字的斷詞
    seg[nchar(seg)>1]
    
    #dat <- read.csv("./cluster_data.csv")
    #dat$Keyword[1]
  })
  
  output$artic.out <- renderTable({
    
    library(jiebaR)
    mixseg = worker()
    seg <- mixseg[input$artic.in]
    
    #去掉只包含一個字的斷詞
    keywords <- seg[nchar(seg)>1]
    #keywords
    df <- as.data.frame(keywords)
    df["Cluster"] <- "No"
    #df[1,]
    
    #判斷段詞比較有機會來自哪一個文章
    dat <- read.csv("./cluster_data.csv")
    #df.dat <- as.data.frame(dat)
    
    for(row in c(1:length(keywords))){
      for (rows.dat in c(1:nrow(dat))){
        if(dat[rows.dat,1] == df[row,1]){
          df[row,2] <- dat[rows.dat,2]
          break
        }
      }
    }
    
    df
    #length(keywords)
    #keywords[1:5]
    
  })
  output$img.pred.out <- renderImage({
    # When input$class.in is 1, filename is ./www/1.jpg
    filename <- normalizePath(file.path('./www', paste('pred_accuracy', '.jpg', sep='')))
    
    # Return a list containing the filename
    list(src = filename, width = 400, height = 150)
  }, deleteFile = FALSE)
}

# Run the application 
shinyApp(ui = ui, server = server)


```

##結果討論
整體上來講，各家媒體對於Elon Musk的報告有很高度的重疊，然而各家的切入點卻稍有不同。

從結果看來，BBC提到較多人工智慧、霍金、人類等字眼，推測BBC在提到Musk時，著重的角度是在人類科技的進步與推展，因此會與創新科技、其他科學家、站在人類發展角度進行報導，進而再提到Musk這號人物。

Epochtimes在報導Musk則較為偏向介紹他個人為主，以這個人為核心進行報導，因此也會提到他所創辦的其他公司，例如：SpaceX，而不僅限於Tesla。

Inside則對Tesla這間公司較感興趣，因此是從Tesla這間公司的角度切入，再介紹到他們的CEO，並且對於財務與公司營運方面較為感興趣，相較之下比較不是提到技術的演進，因此字詞中較常提到：特斯拉私有化、股東、資金、美元、董事。

Techorange則是站在比較中性世界觀的觀點報導Tesla，再進而提到Musk這位領導者，可以發現他的報導方式並不只圍繞著美國電動車的發展，而會把中國的電動車、網路產業納入討論。

透過這次的作業能稍微針對該篇文章可能的來源做預測，然而因為在Cluster時，資料分配的四個cluster重疊頗大，因此預測的準確率並不太大。
